export const fetchProps = {
  code: "",
  title: "",
  add: "",
  addcode: "",
  delet: "",
  deletecode: "",
  sort: "",
  sortcode: "",
  limit: "",
  limitcode: "",
  getsingle: "",
  getsinglecode: "",
  getall: "",
  getallcode: "",
  id: "",
  name: "",
  description: "",
  price: "",
  region: "",
  weight: "",
  flavor_profile: "",
  grind_option: "",
  roast_level: "",
};
